animal = input("안녕하세요! 다음 질문에 답하고 이야기를 완성하세요.\n\n동물을 입력하세요: ")
name = input("이름을 입력하세요: ")
adjective1 = input("형용사를 입력하세요(00(이)고): ")
color1 = input("색을 입력하세요(00색): ")
adjective2 = input("형용사를 입력하세요: ")
noun1 = input("명사를 입력하세요: ")
noun2 = input("명사를 입력하세요: ")
adjective3 = input("형용사를 입력하세요(00은): ")
color2 = input("색을 입력하세요: ")
noun3 = input("명사를 입력하세요: ")
print("아래는 당신이 만든 이야기입니다.\n\n저의 반려동물은", animal + "이며 이름은", name + "입니다.\n" + adjective1 + "(이)고", color1 + "이며", adjective2 + "합니다.\n" + name + "은(는)", noun1 + ",", noun2 + "(을)를 먹습니다.\n" + "가장 좋아하는 장난감은", adjective3, color2, noun3 + "입니다.")